### ISSUE TITLE
Add Lessons

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-chital#19]
### **User Story**
---
As a user when i have lessons selected i should see a button that when clicked populates a form and allows me to add a lesson to the data and it print to the page.

### **AC**
---
**When** the user is logged in and selects lessons a button should be somewhere on that page that says add lesson.
**When** the user clicks the button a form should populate onto the page
**It** should have several input areas that allow the user to put in a class name, source material for the lesson, and when the lesson is taught.
**Then** a submit button should be at the bottom of the form that when clicked pushes the data to firebase and reprints the page with the new lesson added

### **To-Do**
--- 

- [x] Create a new component inside the the lessons component(#23 )named addLesson
- [x] Create a new function that gets lesson data and allows the submitted info to be pushed up (axios.post)
- [x] Create a function that will create a form and print to the dom
- [ ] Create a click event that populates the form when the "Add Lesson" button is pushed
- [x] Create a function that takes the submitted information from the form and turn's it into an object and pushes it to firebase
- [x] Attach the lesson printing function to the submit function(#23 ) so it will reprint the lesson cards

### **Code Example** 
---
**Coming Soon**

### **Wireframe**
---
![image](https://user-images.githubusercontent.com/62913995/87496308-e9aa7a80-c618-11ea-942b-aa48da752b26.png)
