### ISSUE TITLE
Update/Edit Lessons

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-chital#20]
### **User Story**
---
As a user when i'm signed in and have lessons selected i should see a collection of cards. Each card should have two buttons/icons on them. One of these buttons should read or symbolize the editing of the information on that card.

### **AC**
---
**When** the user logins into the page and selects lessons a collection of lesson cards should populate and all cards should have a edit button
**When** the edit button is clicked a form should populate that allows you to input/change the info on that card
**When** submitted it should change the information of that card in the firebase database and then reprint the cards to the dom

### **To-Do**
--- 

- [x] Create a new component inside the lessons component(#23 ) name editLessons
- [x] Create a new file called editLessons
- [x] Create a function that access lesson data(#32 )and enables it to be updated/changed
- [x] Create a function that creates a bootstrap form and prints it to the dom through a click event
- [x] Create a function that accepts the information filled into the form and when submitted submits the change to that data in the firebase database and then reprints the card with the update information

### **Code Example**
--- 
**Coming Soon**
