### ISSUE TITLE
Show Lessons

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-chital#23]
### **User Story**
---
As a user when i login to the page i should see a button for lessons. When i click this button cards should populate the page showing the various lessons offered in the classes at the college.

I should be able to add(#19 ), delete(#21 ), and update/edit(#20 ) lessons on this page.

### **AC**
---
**When** the user logins into the page a lessons button should be on the page
**When** the lessons button is clicked several cards should populate showcasing the lessons being offered at the college
**There** should also be two buttons on each card that allow you to edit/update and delete the lesson
**Finally** there should be a button that adds lessons to the page

### **To-Do**
--- 

- [x] Create a component for lessons
- [x] Create a seed data file with lessons (#32 )
- [x] Create a function that accesses the lessons data from firebase
- [x] Create a function that builds a card and prints it to the dom
- [x] Create a function that loops over the imported data and adds the information to the lessons cards
- [ ] Create buttons/icon that will add a lesson to the page.

### **Code Sample**
---
**Coming Soon**
