### ISSUE TITLE
Student Collection: Show Students

### ISSUE THREAD

**Issue by gwynnemeeks** [nss-evening-cohort-12/nutshell-chital#25]
### **User Story**
---
As a user, when I login to the page, I should see a button for students. When I click the student button, cards should populate the page showing the various lessons offered in the classes at the college.

I should be able to add(#28 ), delete(#26 ), and update/edit(#27 ) students on this page.

### **AC**
---
**When** the user logins into the page, a students button should be on the page
**When** the students button is clicked several cards should populate showcasing the students attending the college
**There** should also be two buttons on each card that allow you to edit student information or delete the student from the college records.
**Finally** there should be a button that adds students to the page

### **To-Do**
--- 

- [x] Create a component for students
- [x] Create a seed data file with lessons (#29 )
- [x] Create a function that accesses the student data from firebase
- [x] Create a function that builds a card and prints it to the DOM
- [x] Create a function that loops over the imported data and adds the information to the student cards
- [x] Create buttons/icon that will add a student to the page.

### **Code Sample**
---
**Coming Soon**
