### ISSUE TITLE
Student Collection: Edit Student

### ISSUE THREAD

**Issue by gwynnemeeks** [nss-evening-cohort-12/nutshell-chital#27]
### **User Story**
---
As a user when I'm signed in and have students selected I should see a collection of cards. Each card should have two buttons/icons on them. One of these buttons use an editing icon. On click, it allows the card information to be edited via a form.

### **AC**
---
**When** the user logins into the page and selects students a collection of student cards should populate and all cards should have an edit button
**When** the edit button is clicked a form should populate that allows you to edit the info on that card
**When** submitted it should change the information of that card in the firebase database and then reprint the cards to the DOM

### **To-Do**
--- 

- [ ] Create a new component inside the student component(#25 ) named editStudents
- [ ] Create a new file called editStudents
- [ ] Create a function that accesses student data(#29 ) and enables it to be updated/changed
- [ ] Create a function that creates/shows a bootstrap form and prints it to the DOM through a click event
- [ ] Create a function that accepts the information filled into the form and when submitted submits the change to that data in the firebase database and then reprints the card with the update information

### **Code Example**
--- 
**Coming Soon**

### **Moqup**
---
![image](https://user-images.githubusercontent.com/63276406/87601748-5413f700-c6bb-11ea-9f5b-ec5c74967035.png)
