### ISSUE TITLE
Student Collection: Add Student

### ISSUE THREAD

**Issue by gwynnemeeks** [nss-evening-cohort-12/nutshell-chital#28]
### **User Story**
---
As a user when I have students selected I should see a button that when clicked populates a form and allows me to add a student to the data and it print to the DOM.

### **AC**
---
**When** the user is logged in and selects students a button should be somewhere towards the top of page that says add lesson.
**When** the user clicks the button a form should populate on the right side of the page
**It** should have several input areas that allow the user to put in a class name, source material for the lesson, and when the lesson is taught.
**Then** a submit button should be at the bottom of the form that when clicked pushes the data to firebase and reprints the page with the new lesson added

### **To-Do**
--- 

- [x] Create a new component inside the the lessons component(#25 )named addStudents
- [ ] Create a new function that gets lesson data and allows the submitted info to be pushed up (axios.post)
- [x] Create a function that will create a form and print to the DOM
- [x] Create a click event that populates the form when the "Add Student" button is pushed
- [ ] Create a function that takes the submitted information from the form and turn's it into an object and pushes it to firebase
- [ ] Attach the student printing function to the submit function(#25  ) so it will reprint the student cards

### **Code Example** 
---
**Coming Soon**

### **Wireframe**
![image](https://user-images.githubusercontent.com/63276406/87601628-13b47900-c6bb-11ea-9192-be3fe8cb89db.png)
