### ISSUE TITLE
Lessons Seed Data

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-chital#32]
**Dev Story**
---
As a developer i should see a json data file named lesson.json. It should contain seed data that has several different lessons listed into it. The json file should be pushed up and stored into a firebase database.

### **AC**
---
**When** the developer looks at the code they should see a db folder. In the folder should be a json filed named lessons
**Then** the developer should be able to go to firebase and look in the database section and see the data from the json file there

### **To-Do**
--- 
- [x] Create a json file in the db folder named lessons
- [x] Create some basic data containing lesson id, lessons name, whether supplies are provided, and the off days of the lesson
- [x] Import file into firebase database

### **Data Example**
---

```
{
    "lesson1": {
       "id": "",
       "name": "",
       "supplieProvided": "",
       "daysOff": "",
   }
};
```
